steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/stbotolphs-291315/stbotolphs", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/stbotolphs-291315/stbotolphs"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=k8s-config
  - --image=gcr.io/stbotolphs-291315/stbotolphs
  - --location=europe-west2
  - --cluster=stbotolphs-gke
