steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    export POSTGRES_DB=`gcloud secrets versions access latest --secret=POSTGRES_DB --format='get(payload.data)' | base64 -d`
    export POSTGRES_USER=`gcloud secrets versions access latest --secret=POSTGRES_USER --format='get(payload.data)' | base64 -d`
    export POSTGRES_PASSWORD=`gcloud secrets versions access latest --secret=POSTGRES_PASSWORD --format='get(payload.data)' | base64 -d`
  # Search and replace variable
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  args:
  - '-c'
  - |
    sed -i 's/%POSTGRES_DB%/'${$POSTGRES_DB}'/g' Dockerfile
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/direct-obelisk-291614/stbotolphs", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/direct-obelisk-291614/stbotolphs"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=k8s-config
  - --image=gcr.io/direct-obelisk-291614/stbotolphs
  - --location=europe-west2
  - --cluster=stbotolphs-gke
