apiVersion: apps/v1
kind: Deployment
metadata:
  name: stbotolphs
  namespace: stbotolphs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stbotolphs
  template:
    metadata:
      labels:
        app: stbotolphs
    spec:
      containers:
      - name: stbotolphs
        image: gcr.io/stbotolphs-291315/stbotolphs
        ports:
        - containerPort: 8080
