apiVersion: apps/v1
kind: Deployment
metadata:
  name: stbotolphs
  namespace: stbotolphs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stbotolphs
  template:
    metadata:
      labels:
        app: stbotolphs
    spec:
      containers:
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        command: ["/cloud_sql_proxy",
                  "--dir=/cloudsql",
                  "-instances=direct-obelisk-291614:europe-west2:postgres-instance-559d76a1=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        securityContext:
          # The default Cloud SQL proxy image runs as the
          # "nonroot" user and group (uid: 65532) by default.
          runAsNonRoot: true        
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql         
          readOnly: true
  
      - name: stbotolphs
        image: gcr.io/direct-obelisk-291614/stbotolphs
        ports:
        - containerPort: 8080

      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
