apiVersion: v1
kind: Service
metadata:
  name: stbotolphs-nlb-service
  namespace: stbotolphs
spec:
  selector:
    app: stbotolphs
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: mailhog-smtp-nlb-service
  namespace: stbotolphs
spec:
  selector:
    app: mailhog
  type: ClusterIP
  ports:
  - port: 1025
    targetPort: 1025
---
apiVersion: v1
kind: Service
metadata:
  name: mailhog-webadminsmtp-nlb-service
  namespace: stbotolphs
spec:
  selector:
    app: mailhog
  type: ClusterIP
  ports:
  - port: 8025
    targetPort: 8025
